# Generated by Django 6.0 on 2025-12-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("about", models.CharField(max_length=50)),
                ("website", models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="storyline",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
