# Generated by Django 6.0 on 2025-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_streamplatform_alter_watchlist_storyline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamplatform",
            name="website",
            field=models.URLField(max_length=300),
        ),
    ]
