# Generated by Django 6.0 on 2025-12-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_streamplatform_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="streamplatform",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streamplatform",
                to="api.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
